dialect "mvel"

declare Creature
	id : int @key
end

declare Ability
	name : String
	food : int
end

declare Carnivorous extends Ability
end

declare Action
	creature : Creature @key
end

declare EatFood extends Action
end

declare EatCreature extends Action
	sacrifice : Creature @key
end

// Things


declare Thing
    id : long
end   

declare Character extends Thing
    name : String @key
end  

declare Item extends Thing
    name : String @key
    fixed : boolean
end

declare Room extends Thing   
    name : String @key
end
        
declare Door extends Thing
   fromRoom : Room @key
   toRoom : Room @key
end  

declare Key extends Thing
end

declare Lock extends Thing
    key : Key @key
    door : Door @key
    status : String
end

// State
declare Location
    thing : Thing @key
    target : Thing @key
end

declare Holding
   character : Character @key
   thing : Thing @key
end   

// Events
declare GameEvent
   @role(event)
end

declare CharacterSelectedEvent extends GameEvent
   @role(event)
   character : Character @key
end
 
declare ExitEvent extends GameEvent
   @role(event)
   character : Character @key   
   room : Room @key
end

declare EnterEvent extends GameEvent
   @role(event)
   character : Character @key
   room : Room @key
end

declare PickupEvent extends GameEvent
   @role(event)
   character : Character @key
   thing : Thing @key
end

declare DropEvent extends GameEvent
   @role(event)
   character : Character @key
   thing : Thing @key
end